services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: grails
      MYSQL_USER: grails
      MYSQL_DATABASE: hello
    ports:
      - 3306:3306